name: rire_noir
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  appinio_swiper: ^2.1.0
  google_fonts: ^6.2.1
  web_socket_channel: ^2.4.4
  api:
    path: ./api
  go_router: ^13.2.2
  dio: ^5.4.2+1
  device_info_plus: ^10.0.1
  uuid: ^4.3.3
  flutter_bloc: ^8.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  pretty_qr_code: ^3.3.0
  sensors: ^2.0.3
  flutter_localizations:
    sdk: flutter
  intl: any
  platform_device_id: ^1.0.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/core/assets/svg/
    - lib/core/assets/image/
    - lib/core/assets/lottie/

