name: api
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: ^3.3.3
dependencies:
  equatable: ^2.0.5
  shelf_cors_headers: ^0.1.5
  shelf_plus: ^1.9.1
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
